//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int StudentId { get; set; }
        public int AttendanceTypeId { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Value { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public System.DateTime AttendanceDate { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual Student Student { get; set; }
    }
}
