//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MercuryEntities : DbContext
    {
        public MercuryEntities()
            : base("name=MercuryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceType> AttendanceTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Suspension> Suspensions { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<PhoneDistrict_X> PhoneDistrict_X { get; set; }
        public virtual DbSet<PhoneSchool_X> PhoneSchool_X { get; set; }
        public virtual DbSet<PhoneStaff_X> PhoneStaff_X { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStaff_X> UserStaff_X { get; set; }
        public virtual DbSet<AcademicTerm> AcademicTerms { get; set; }
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
    
        public virtual ObjectResult<sp_GetDistricts_Result> sp_GetDistricts(Nullable<int> districtId)
        {
            var districtIdParameter = districtId.HasValue ?
                new ObjectParameter("DistrictId", districtId) :
                new ObjectParameter("DistrictId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDistricts_Result>("sp_GetDistricts", districtIdParameter);
        }
    
        public virtual ObjectResult<sp_GetSchools_Result> sp_GetSchools(Nullable<int> schoolId)
        {
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSchools_Result>("sp_GetSchools", schoolIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStaff_Result> sp_GetStaff(Nullable<int> staffId)
        {
            var staffIdParameter = staffId.HasValue ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStaff_Result>("sp_GetStaff", staffIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentAttendance_Result> sp_GetStudentAttendance(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentAttendance_Result>("sp_GetStudentAttendance", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudents_Result> sp_GetStudents(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudents_Result>("sp_GetStudents", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentSuspension_Result> sp_GetStudentSuspension(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentSuspension_Result>("sp_GetStudentSuspension", studentIdParameter);
        }
    
        public virtual ObjectResult<sp_GetStudent_DashboardView_Result> sp_GetStudent_DashboardView(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudent_DashboardView_Result>("sp_GetStudent_DashboardView", studentIdParameter);
        }
    }
}
