//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStaff_X
    {
        public int UserId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    }
}
