//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public System.Guid UserKey { get; set; }
        public System.DateTime CreateDt { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
        public string Email { get; set; }
        public string Passcode { get; set; }
        public string IpAddress { get; set; }
    }
}
